name: wasm_wit_component_example
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  wasm_run: ^0.0.1
  wasm_wit_component: ^0.0.1

dev_dependencies:
  test: ^1.24.2
  very_good_analysis: ^4.0.0