[package]
name = "rust_wasi_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ['cdylib']

[[bin]]
path = "src/main.rs"
name = "rust_wasi_example_bin"

[dependencies]
