version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/wasm_run"
    schedule:
      interval: weekly
  # - package-ecosystem: pub
  #   directory: "/packages/wasm_run/example"
  #   schedule:
  #     interval: weekly
  - package-ecosystem: pub
    directory: "/packages/wasm_run_flutter"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/wasm_run_flutter/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/wasm_run/native"
    schedule:
      interval: weekly
