version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/wasmit"
    schedule:
      interval: weekly
  # - package-ecosystem: pub
  #   directory: "/packages/wasmit/example"
  #   schedule:
  #     interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_wasmit"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_wasmit/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/wasmit/native"
    schedule:
      interval: weekly
