name: wasmi

repository: https://github.com/juancastillo0/wasm_interpreter

packages:
  - packages/**

command:
  bootstrap:
    hooks:
      pre: dart compile exe "scripts/config_api.dart" && chmod +x "scripts/config_api.exe"

scripts:
  analyze:
    exec: flutter analyze . --no-fatal-infos
    description: Analyze a specific package in this project.

  check-format:
    exec: dart format --set-exit-if-changed .
    description: Check the format of a specific package in this project.

  format:
    exec: dart format .
    description: Format a specific package in this project.

  version:
    description: Updates version numbers in all build files
    run: bash scripts/version.sh

  build:
    run: melos run build:apple && melos run build:android && melos run build:other
    description: Build all native libraries for the project.
    env:
      WASM_BUILD_RUST_WASI_EXAMPLE: false

  build:apple:
    run: bash scripts/build-apple.sh
    description: Build the XCFramework for iOS and macOS.

  build:android:
    run: bash scripts/build-android.sh
    description: Build the .tar.gz for Android.

  build:other:
    run: bash scripts/build-other.sh
    description: Build the .tar.gz for all other platforms.

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: cd packages/wasmi && dart test test -c source
    description: Run Dart tests for a specific package in this project.

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dir-exists: test

  test:coverage:
    run: cd packages/wasmi && dart pub global activate coverage && dart pub global run coverage:test_with_coverage -- -c source
    description: Run all Dart & Flutter tests in this project and collect coverage.
