name: rust_crypto
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/juancastillo0/wasm_run

environment:
  sdk: ^3.0.0

dependencies:
  wasm_run: ^0.0.1
  wasm_wit_component: ^0.0.1


dev_dependencies:
  cryptography: ^2.5.0
  crypto: ^3.0.3
  webcrypto: ^0.5.3
  # r_crypto: ^0.5.0
  # cryptography_flutter: ^2.3.0

  dargon2: ^3.2.1
  argon2: ^1.0.1

  # aes_gcm
  pointycastle: ^3.7.3
  hashlib: ^1.11.4 # benchmark https://pub.dev/packages/hashlib
  # Blake3

  lints: ^2.0.0
  test: ^1.21.0
