name: image_rs
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/juancastillo0/wasm_run

environment:
  sdk: ^3.1.0-63.1.beta

dependencies:
  wasm_run: ^0.0.1
  wasm_wit_component: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
