name: typesql_parser
description: SQL parser, AST and visitors
version: 0.0.1
repository: https://github.com/juancastillo0/wasm_run
topics:
  - wasm
  - wit
  - sql
  - parser
  - ast

environment:
  sdk: ^3.0.0

flutter:
  assets:
    - lib/assets/

dependencies:
  wasm_run: ^0.1.0
  wasm_wit_component: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
