[package]
name = "wasmi_dart"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.72.*"

[dependencies]
flutter_rust_bridge = "1.72.*"
wasmi = "0.29.0"
wat = "1.0.61"
anyhow = "1.0.0"
once_cell = "1.0.0"