[package]
name = "wasmi_dart"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.72.*"

[dependencies]
flutter_rust_bridge = "1.72.*"
anyhow = "1.0.0"
once_cell = "1.0.0"
wat = "1.0.61"

wasi-common = "7.0.0"
cap-std = "1.0.13"
wasmtime = "7.0.0"
wasmtime-wasi = "7.0.0"
# wasmtime-types = "7.0.0"

[features]
default = ["wasmtime"]
wasmi = []
wasmtime = []
