name: typesql_generator
description: SQL types code generator from .sql files to Dart queries and models
version: 0.0.1
repository: https://github.com/juancastillo0/wasm_run
topics:
  - sql
  - codegen

environment:
  sdk: ^3.0.0

dependencies:
  typesql: ^0.0.1
  build: ^2.4.1
  recase: ^4.1.0
  dart_style: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.6
  build_config: ^1.1.1
  lints: ^2.0.0
  test: ^1.21.0
