[package]
name = "wasm_parser_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]
wasm-compose = "0.2.17"
wasm-metadata = "0.8.0"
wasmparser = "0.107.0"
wasmprinter = "0.2.59"
wast = "60.0.0"
wat = "1.0.66"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.7.0", rev = "131746313de2f90d2688afbbc40c4a7ca309fe0d" }
wit-component = "0.11.0"
