name: typesql
description: SQL type utilities and helpers for Dart model code generator and query execution
version: 0.0.1
repository: https://github.com/juancastillo0/wasm_run
topics:
  - sql

environment:
  sdk: ^3.0.0

dependencies:
  typesql_parser: ^0.0.1
  meta: ^1.9.1
  sqlite3: ^2.0.0
  recase: ^4.1.0
  wasm_wit_component: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
