name: wasm_run_example
description: Demonstrates how to use the wasm_run package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  wasm_run:
    path: ../
  test: ^1.21.0

dev_dependencies:
  very_good_analysis: ^4.0.0