name: wasmit_example
description: Demonstrates how to use the wasmit package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  wasmit:
    path: ../
  test: ^1.21.0