[package]
name = "wasm_run_dart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.4"

[dependencies]
flutter_rust_bridge = "1.82.4"
anyhow = "1.0.75"
once_cell = "1.18.0"
wat = "1.0.77"

wasmi = "0.31.0"
wasi-common = { version = "2.0.2", optional = true } # the latest is 7.0.0, but it's not compatible with wasmi_wasi
cap-std = { version = "0.26.1", optional = true }
wasmi_wasi = { version = "0.31.0", optional = true }

[features]
default = ["wasmi", "wasi"]
wasi = ["dep:wasmi_wasi", "dep:wasi-common", "dep:cap-std"]
wasmi = []
wasmtime = []
