name: Create Release(s)

on:
  workflow_dispatch:
    inputs:
      version_parameters:
        description: 'Parameters to pass to "melos version" (major, minor, patch or build) or an exact version for one or more packages'
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.name "Juan Manuel Castillo"
          git config user.email "42351046+juancastillo0@users.noreply.github.com"
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2

      - name: Create the new version(s)
        run: melos version --yes --ignore '*' \
          --manual-version wasmit:${{ inputs.version_parameters }} \
          --manual-version flutter_wasmit:${{ inputs.version_parameters }}

      - name: Push created version commit
        run: git push
      - name: Push modified tags
        run: git push --tags
